#!/bin/sh -e


sed -i '/gen_thumbnailer = custom_target/,/^$/c\
  gen_thumbnailer = custom_target(\x27thumbnailer\x27,\
                                  output: \x27gdk-pixbuf-thumbnailer.thumbnailer\x27,\
                                  input: \x27gdk-pixbuf-thumbnailer.thumbnailer.in\x27,\
                                  build_by_default: false,\
                                  command: [\x27echo\x27, \x27disabled\x27],\
                                  )' gdk-pixbuf/meson.build

sed -i 's/build_by_default: true/build_by_default: false/' gdk-pixbuf/meson.build

meson setup  \
    -Dprefix=/usr \
    -Dsysconfdir=/etc \
    -Dmandir=/usr/share/man \
    -Ddebug=false \
    -Dglycin=disabled \
    -Djpeg=enabled \
    -Dpng=enabled \
    -Dtiff=disabled \
    -Dgtk_doc=false \
    -Dman=false \
    -Dgio_sniffing=false \
    -Dtests=false \
    -Dinstalled_tests=false \
    -Dbuiltin_loaders=all \
    -Dwrap_mode=nofallback \
    build

meson -C build samu -v
meson -C build install
