#!/bin/sh -e
export DESTDIR="$1"

muon setup \
    -Dprefix=/usr \
    -Dsysconfdir=/etc \
    -Dmandir=/usr/share/man \
    -Ddebug=false \
    -Dglycin=disabled \
    -Djpeg=enabled \
    -Dpng=enabled \
    -Dtiff=disabled \
    -Dgtk_doc=false \
    -Dman=false \
    -Dgio_sniffing=false \
    -Dtests=false \
    -Dwrap_mode=nofallback \
    output

ninja -C output
ninja -C output install
