#!/bin/sh -e

export CXXFLAGS="-O3 -pipe -march=native -std=gnu+11"
export CFLAGS="-O3 -pipe -march=native -std=gnu11"

./configure \
    --prefix=/usr \
    --disable-static

make
make DESTDIR="$1" install
