#!/bin/sh -e

for p in *.patch; do
    patch -p1 < "$p"
done

sed '/UNZIP/d' toolkit/moz.configure > _
mv -f _ toolkit/moz.configure

sed 's/\("files":{\)[^}]*/\1/' third_party/rust/encoding_rs/.cargo-checksum.json > _
	mv -f _ third_party/rust/encoding_rs/.cargo-checksum.json

export CXXSTDLIB=c++
export CFLAGS="$CFLAGS -fvisibility=hidden"
export CXXFLAGS="$CXXFLAGS -fvisibility=hidden -fvisibility-inlines-hidden"

: > config/gcc_hidden.h

# Fix pid_t not defined on musl in libwebrtc
sed -i '1i #include <sys/types.h>' \
    third_party/libwebrtc/modules/desktop_capture/desktop_capturer.h

# Instruct the compiler to trim absolute paths in resulting binaries and instead
# change them to relative paths ($PWD/... ./...).
export RUSTFLAGS="$RUSTFLAGS --remap-path-prefix=$PWD=."

export LDFLAGS="$LDFLAGS -Wl,--no-as-needed"
export RUSTFLAGS="$RUSTFLAGS -Cdebuginfo=0"
export MACH_BUILD_PYTHON_NATIVE_PACKAGE_SOURCE=system
export MOZ_DEBUG_FLAGS=-g0
export MOZBUILD_STATE_PATH="$PWD/state"
export MOZ_NOSPAM=1

cat > .mozconfig << EOF
ac_add_options --prefix=/usr
ac_add_options --libdir=/usr/lib
ac_add_options --enable-default-toolkit=cairo-gtk3-wayland-only
ac_add_options --enable-strip
ac_add_options --enable-release
ac_add_options --enable-rust-simd
ac_add_options --enable-audio-backends=alsa
ac_add_options --enable-install-strip
ac_add_options --enable-official-branding
ac_add_options --enable-application=browser
ac_add_options --enable-optimize
ac_add_options --with-system-ffi
ac_add_options --with-system-jpeg
ac_add_options --with-system-libvpx
ac_add_options --with-system-nspr
ac_add_options --with-system-nss
ac_add_options --with-system-pixman
ac_add_options --with-system-png
ac_add_options --with-system-webp
ac_add_options --with-system-zlib
ac_add_options --without-wasm-sandboxed-libraries
ac_add_options --disable-eme
ac_add_options --disable-dbus
ac_add_options --disable-tests
ac_add_options --disable-vtune
ac_add_options --disable-updater
ac_add_options --disable-jemalloc
ac_add_options --disable-elf-hack
ac_add_options --disable-callgrind
ac_add_options --disable-profiling
ac_add_options --disable-necko-wifi
ac_add_options --disable-crashreporter
ac_add_options --disable-accessibility
ac_add_options --disable-debug
ac_add_options --disable-debug-symbols
ac_add_options --disable-parental-controls
ac_add_options --disable-system-extension-dirs
EOF

sed -i "s/SharedLibrary('mozavutil')/Library('mozavutil')/" \
    media/ffvpx/libavutil/moz.build

sed -i "/SYMBOLS_FILE.*=.*'avutil.symbols'/d" \
    media/ffvpx/libavutil/moz.build
sed -i "/^NoVisibilityFlags()$/d" \
    media/ffvpx/libavutil/moz.build
sed -i "s/SharedLibrary('mozsqlite3')/Library('mozsqlite3')/" \
    config/external/sqlite/moz.build
sed -i "/^    'log2_tab\.c',\?$/d" media/ffvpx/libavcodec/moz.build
sed -i "/^    'reverse\.c',\?$/d" media/ffvpx/libavcodec/moz.build
sed -i "s/SharedLibrary('mozsqlite3')/Library('mozsqlite3')/" \
    config/external/sqlite/moz.build
sed -i "/SYMBOLS_FILE/d" config/external/sqlite/moz.build
sed -i "/NoVisibilityFlags/d" config/external/sqlite/moz.build

sed -i "s/SharedLibrary('mozsqlite3')/Library('mozsqlite3')/" \
    security/nss/lib/sqlite/sqlite.gyp 2>/dev/null || true

sed -i "s/SharedLibrary('opus')/Library('opus')/" \
    media/libopus/moz.build
sed -i "s/SharedLibrary('mozopus')/Library('mozopus')/" \
    media/libopus/moz.build
sed -i "/SYMBOLS_FILE/d" media/libopus/moz.build
sed -i "/NoVisibilityFlags/d" media/libopus/moz.build
sed -i '/DEFINES\["OPUS_EXPORT"\] = ""/d' media/libopus/moz.build
sed -i "/SYMBOLS_FILE/d" config/external/gkcodecs/moz.build
sed -i 's/GeckoSharedLibrary("gkcodecs")/Library("gkcodecs")/' \
    config/external/gkcodecs/moz.build
sed -i '/SYMBOLS_FILE = "gkcodecs.symbols"/d' \
    config/external/gkcodecs/moz.build
sed -i '/SHARED_LIBRARY_NAME = "gkcodecs"/d' \
    config/external/gkcodecs/moz.build
./mach build "${MAKEFLAGS:-}"
DESTDIR="$1" ./mach install

# Remove a lot of uneeded "stuff".
rm -rf \
    "$1/usr/include" \
    "$1/usr/lib/firefox-devel" \
    "$1/usr/share/idl"
