#!/bin/sh -e

for p in *.patch; do
    patch -p1 < "$p"
done

sed '/UNZIP/d' toolkit/moz.configure > _
mv -f _ toolkit/moz.configure

sed -i 's|^use core::simd::Select;|// use core::simd::Select; // commented: nightly-only, bug upstream|' \
    third_party/rust/encoding_rs/src/x_user_defined.rs

sed -i 's|^#!\[cfg_attr(feature = "simd-accel", feature(core_intrinsics, portable_simd))\]|// &|' \
    third_party/rust/encoding_rs/src/lib.rs

find third_party/rust/encoding_rs/src -name '*.rs' -exec \
    sed -i 's|feature = "simd-accel"|any()|g' {} \;

sed 's/\("files":{\)[^}]*/\1/' \
    third_party/rust/encoding_rs/.cargo-checksum.json > _
mv -f _ third_party/rust/encoding_rs/.cargo-checksum.json


# Workaround pra libc++ 22 + fmt (llvm issue #79027)
: > config/gcc_hidden.h

# Fix pid_t não definido no musl em libwebrtc
sed -i '1i #include <sys/types.h>' \
    third_party/libwebrtc/modules/desktop_capture/desktop_capturer.h

export CXXSTDLIB=c++
export RUSTFLAGS="$RUSTFLAGS --remap-path-prefix=$PWD=. -Cdebuginfo=0"
export LDFLAGS="$LDFLAGS -Wl,-rpath=/usr/lib/firefox,--enable-new-dtags,--no-as-needed"
export MACH_BUILD_PYTHON_NATIVE_PACKAGE_SOURCE=system
export MOZ_DEBUG_FLAGS=-g0
export MOZBUILD_STATE_PATH="$PWD/state"
export MOZ_NOSPAM=1

cat > .mozconfig << EOF
ac_add_options --prefix=/usr
ac_add_options --libdir=/usr/lib
ac_add_options --enable-default-toolkit=cairo-gtk3-wayland-only
ac_add_options --enable-strip
ac_add_options --enable-release
ac_add_options --enable-audio-backends=alsa
ac_add_options --enable-install-strip
ac_add_options --enable-official-branding
ac_add_options --enable-application=browser
ac_add_options --enable-optimize
ac_add_options --with-system-ffi
ac_add_options --with-system-jpeg
ac_add_options --with-system-libvpx
ac_add_options --with-system-nspr
ac_add_options --with-system-nss
ac_add_options --with-system-pixman
ac_add_options --with-system-png
ac_add_options --with-system-webp
ac_add_options --with-system-zlib
ac_add_options --without-wasm-sandboxed-libraries
ac_add_options --disable-rust-simd
ac_add_options --disable-eme
ac_add_options --disable-dbus
ac_add_options --disable-tests
ac_add_options --disable-vtune
ac_add_options --disable-updater
ac_add_options --disable-jemalloc
ac_add_options --disable-elf-hack
ac_add_options --disable-callgrind
ac_add_options --disable-profiling
ac_add_options --disable-necko-wifi
ac_add_options --disable-crashreporter
ac_add_options --disable-accessibility
ac_add_options --disable-debug
ac_add_options --disable-debug-symbols
ac_add_options --disable-parental-controls
ac_add_options --disable-system-extension-dirs
EOF

./mach build "${MAKEFLAGS:-}"
DESTDIR="$1" ./mach install

rm -rf \
    "$1/usr/include" \
    "$1/usr/lib/firefox-devel" \
    "$1/usr/share/idl"
