#!/bin/sh -e
export DESTDIR="$1"

meson setup \
    -Dprefix=/usr \
    -Dbuildtype=release \
    -Dx11=disabled \
    -Dglx=disabled \
    -Degl=true \
    -Dgles1=true \
    -Dgles2=true \
    output

ninja -C output
ninja -C output install
