#!/bin/sh -e
cat <<'MSG'

  OpenJDK 17 JRE instalado em /usr/lib/jvm/java-17-openjdk/
  (Build musl/Alpine - compativel com KISS Linux nativo)

  Executaveis disponiveis com sufixo '17':
    java17, keytool17, rmiregistry17

  Para definir como java padrao do sistema:
    kiss a openjdk17-jre /usr/bin/java /usr/lib/jvm/java-17-openjdk/bin/java

MSG
