#!/bin/sh -e
jvmdir="$1/usr/lib/jvm/java-25-openjdk"
install -d "$jvmdir"

cp -a . "$jvmdir/"

# Remove man pages
rm -rf "$jvmdir/man"

install -d "$1/usr/bin"
for bin in java keytool rmiregistry; do
    [ -f "$jvmdir/bin/$bin" ] && \
        ln -sf "/usr/lib/jvm/java-25-openjdk/bin/$bin" \
               "$1/usr/bin/${bin}25"
done
