#!/bin/sh -e

sed 's/HAVE_LIBELF/HAVE_KISS/' gio/meson.build > _
mv -f _ gio/meson.build

sed 's/libmount_dep.found()/false/' meson.build > _
mv -f _ meson.build

export AR=llvm-ar
export NM=llvm-nm
export RANLIB=llvm-ranlib
export DESTDIR="$1"

: > glib/tests/meson.build
: > tests/meson.build
: > gobject/tests/mesom.build
: > gio/tests/meson.build
: > fuzzing/meson.build
: > fuzzing/meson.build

CC=clang CXX=clang++ meson setup \
    -Dprefix=/usr \
    -Dlibexecdir=/usr/lib \
    -Dlibmount=disabled \
    -Dinstalled_tests=false \
    -Ddefault_library=both \
    -Dman=false \
    -Dtests=false \
    -Dlibelf=disabled \
    -Dnls=disabled \
    -Dsysprof=disabled \
    build

ninja -C build
ninja -C build install

rm -rf "$1/usr/bin/gdbus"
