#!/bin/sh -e
# Instala o JRE 8 (binario pre-compilado glibc) no diretorio destino.
# O KISS ja remove o componente raiz do tarball antes de executar este script,
# entao o diretorio atual contem bin/, lib/, etc. diretamente.
#
# $1 = DESTDIR   $2 = versao

jvmdir="$1/usr/lib/jvm/java-8-openjdk"
install -d "$jvmdir"

# Copia todo o conteudo extraido
cp -a . "$jvmdir/"

# Remove man pages (economiza espaco)
rm -rf "$jvmdir/man"

# Cria symlinks versionados em /usr/bin
install -d "$1/usr/bin"
for bin in java javaws keytool orbd pack200 \
           rmid rmiregistry servertool tnameserv unpack200; do
    [ -f "$jvmdir/bin/$bin" ] && \
        ln -sf "/usr/lib/jvm/java-8-openjdk/bin/$bin" \
               "$1/usr/bin/${bin}8"
done
