#!/bin/sh -e
export DESTDIR="$1"

sed '/rust_std=2021/d' meson.build > _
mv -f _ meson.build

pkg-config --exists libglvnd || glvnd_enabled=false

meson setup \
    -Dprefix=/usr \
    -Dsysconfdir=/etc \
    -Dmandir=/usr/share/man \
    -Dlocalstatedir=/var \
    -Dbuildtype=release \
    -Dglx-read-only-text=true \
    -Dplatforms=wayland \
    -Dglx=disabled \
    -Degl=enabled \
    -Dvalgrind=false \
    -Dzstd=disabled \
    -Dglvnd="${glvnd_enabled:-true}" \
    -Dvideo-codecs=vc1dec,h264dec,h264enc,h265dec,h265enc \
    -Dvulkan-drivers='' \
    -Dcpp_link_args='-fuse-ld=lld -lc++abi' \
    output

ninja -C output
ninja -C output install
