#!/bin/sh -e

export CC=clang
export CXX=clang++
export CXXFLAGS="$CXXFLAGS -stdlib=libc++"
export LDFLAGS="$LDFLAGS -stdlib=libc++ -lc++abi -fuse-ld=lld"

if command -v cmake >/dev/null; then
    export DESTDIR="$1"

    cmake -B build \
        -DCMAKE_C_COMPILER=clang \
        -DCMAKE_CXX_COMPILER=clang++ \
        -DCMAKE_INSTALL_PREFIX=/usr \
        -DCMAKE_BUILD_TYPE=Release \
        -DCMAKE_USE_SYSTEM_CURL=True \
        -DCMAKE_USE_SYSTEM_EXPAT=True \
        -DCMAKE_USE_SYSTEM_ZLIB=True \
        -DCMAKE_USE_SYSTEM_BZIP2=True \
        -DBUILD_CursesDialog=OFF \
        -DBUILD_TESTING=OFF

    cmake --build   build
    cmake --install build

else
    ./configure \
        --prefix=/usr \
        --system-curl \
        --system-expat \
        --system-zlib \
        --system-bzip2 \
        --parallel="$(grep -scF 'core id' /proc/cpuinfo)" -- \
        -DBUILD_CursesDialog=OFF

    make
    make DESTDIR="$1" install
fi

rm -rf \
    "$1/usr/doc" \
    "$1/usr/share/cmake"*/Help \
    "$1/usr/share/bash-completion"
