#!/bin/sh -e

cmake -B build -S . \
    -DCMAKE_INSTALL_PREFIX=/usr \
    -DCMAKE_INSTALL_SBINDIR=/usr/bin \
    -DCMAKE_INSTALL_MANDIR=/usr/share/man \
    -DCMAKE_INSTALL_SYSCONFDIR=/etc \
    -DCMAKE_INSTALL_LOCALSTATEDIR=/var \
    -DENABLE_NLS=OFF \
    -DENABLE_DAEMON=ON \
    -DENABLE_UTP=ON \
    -DWITH_SYSTEMD=OFF \
    -DENABLE_GTK=OFF

cmake --build build

make -C build DESTDIR="$1" install
