#!/bin/sh -e
export DESTDIR="$1"
meson setup \
    -Dprefix=/usr \
    -Ddefault_font_path=/usr/share/fonts \
    -Dsha1=libcrypto \
    -Dinput_thread=true \
    -Ddri3=true \
    -Dxdmcp=false \
    -Dsecure-rpc=false \
    -Dglamor=true \
    -Dglx=true \
    output
ninja -C output
ninja -C output install
