#!/bin/sh -e

export DESTDIR="$1"
sed '/rust_std=2021/d' meson.build > _
mv -f _ meson.build
sed -i "s/version *: *'> *2\.3'//" meson.build
find src -type f \( -name '*.y' -o -name '*.yy' \) -exec sed -i \
        -e 's/%define[[:space:]]\+api\.pure[^$]*/%pure-parser/' \
            -e '/%define/d' \
                {} +
                    find src -name meson.build -exec sed -i \
        "s|'--defines=@OUTPUT1@'|'-H', '@OUTPUT1@'|g" {} +                    
pkg-config --exists libglvnd || glvnd_enabled=false
meson setup \
    -Dprefix=/usr \
    -Dsysconfdir=/etc \
    -Dmandir=/usr/share/man \
    -Dlocalstatedir=/var \
    -Dbuildtype=release \
    -Dglx-read-only-text=true \
    -Dplatforms=x11,wayland \
    -Dglx=dri \
    -Degl=enabled \
    -Dgles1=true \
    -Dgles2=true \
    -Dvalgrind=false \
    -Dzstd=disabled \
    -Dglvnd=true \
    -Dcpp_rtti=false \
    -Dvideo-codecs=vc1dec,h264dec,h264enc,h265dec,h265enc \
    -Dvulkan-drivers='' \
    -Dllvm=enabled \
    -Dcpp_link_args='-fuse-ld=lld -lc++abi' \
    output

sed -i -e 's/ -Wno-deprecated//g' -e 's/--defines=\([^ ]*\)/-H \1/g' output/build.ninja



ninja -C output
ninja -C output install
