#!/bin/sh -e

export DESTDIR="$1"

patch -p1 < no-fribidi.patch

# Disable download of missing (optional) dependencies
# during the build. This cannot be turned off otherwise.
rm -rf subprojects

: > tests/muon.build
: > examples/muon.build
: > docs/muon.build

muon setup \
    -Dprefix=/usr \
    -Dgtk_doc=false \
    -Dxft=disabled \
    -Dintrospection=disabled \
    build

ninja -C build
ninja -C build install
