#!/bin/sh -e

export DESTDIR="$1"

muon setup \
    -Dprefix=/usr \
    -Dtee=enabled \
    -Dxcb=disabled \
    -Dxlib=disabled \
    -Dxlib-xcb=disabled \
    -Dtests=disabled \
    output

ninja -C output
ninja -C output install
